remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Vero Arriola
description: Colección de presentaciones utilizadas para la creación de material didáctico en línea.

